### ISSUE TITLE
Change Transaction History - Not Working

### ISSUE THREAD

**Issue by alk0rani** [lilhumza/Bank#11]
Updated **bankTeller** so the user needs to answer the security questions before accessing the bankTeller. However, for some reason, when you enter "1" to change transaction history, it skips it and lists the bankTeller options. Can you please fix this? @Draftyshark

**Comment by ghost** [comment]
Thats cause the transactionHistory is reading the security questions instead of the acutal transactionHistory

**Comment by ghost** [comment]
Edit: Im blind lmao didnt see the for loop

**Comment by alk0rani** [comment]
How is it reading the security questions instead of the transactionHistory? It shouldn't be? (´･_･`)

**Comment by alk0rani** [comment]
It was a stupid mistake. I fixed it.

**Comment by ghost** [comment]
I just fixed it too

**Comment by ghost** [comment]
What did you do?

**Comment by ghost** [comment]
Yup that was it
