### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by alk0rani** [lilhumza/Bank#12]
If you already know your accountNum + PIN and try to sign in **right at the start of the program** there will be a few bugs.
1)  When accessing the bankTeller, it won't print the security questions and it'll say **null**.
2) When you log out, it takes you to the main menus and then says 

> Exception in thread "main" java.lang.IllegalStateException: Scanner closed

Also, I think that we should have it so that when the user signs up, it automatically logs them in. That's how most services work. If you can't do that, it's not a big deal. @Draftyshark

**Comment by ghost** [comment]
Try with new bank.java

**Comment by alk0rani** [comment]
The log out has been fixed, the security questions have been not. @Draftyshark

**Comment by ghost** [comment]
Need input values to recreate the bug

**Comment by alk0rani** [comment]
It prints null because the answers to the security questions are only created when the user signs up I think.

**Comment by ghost** [comment]
works fine on my pc tho?

**Comment by alk0rani** [comment]
Fr? Even when you sign in first thing running the program?

**Comment by ghost** [comment]
just tried that, it says null :(

**Comment by alk0rani** [comment]
Dang. :( Well if you could somehow fix it, that'd be nice. @Draftyshark 
Also I think I'm giving up on the binarySearch for now until we can make sure that everything works.

**Comment by ghost** [comment]
Try new bankteller

**Comment by alk0rani** [comment]
It works, thanks! Now we just need the transaction history to print the transactions rather than the security question answers (e.g. [b, b, b]). @Draftyshark
