### ISSUE TITLE
InputMismatchException in Java

### ISSUE THREAD

**Issue by alk0rani** [lilhumza/Bank#13]
Regarding the InputMisMatch exception (when the user enters a String instead of an int), I have a lot of issues implementing it and I can't seem to figure it out. Can you please try to add it to the code, I don't know how to make it work. Also, there are several places in the code where it is needed, and not just when the user enters their PIN. @Draftyshark 

If you don't have enough time to do it, let's just not add it and be under the assumption that the user will enter the correct primitive values when asked.

**Comment by ghost** [comment]
added, please test

**Comment by alk0rani** [comment]
Doesn't work @Draftyshark.

**Comment by alk0rani** [comment]
Was this fixed btw, I don't remember.

**Comment by ghost** [comment]
sadly no

**Comment by alk0rani** [comment]
oh okay, we'll try to get that to work tomorrow too maybe - night

**Comment by ghost** [comment]
Fixed, but contains a tiny bug. gn
