### ISSUE TITLE
Bank Balance

### ISSUE THREAD

**Issue by alk0rani** [lilhumza/Bank#15]
Alright, it doesn't delete the transaction history but for some reason, the balance of the account isn't updating in the file when you do a withdrawal.
Also, when you enter your account pin, after doing that, it makes you click "enter" to continue to the next step.
Anyways, we're almost done. If you can fix these it'd be great, and then we spend the rest of class organizing code.

**Comment by ghost** [comment]
AccountPin is an easy fix. Imma just remove the scanner and use  bufferreader instead

**Comment by ghost** [comment]
I’ll fix the withdraw bug in class

**Comment by alk0rani** [comment]
It is lmao, I'm just a bit busy rn studying for biology. Thanks dude!
