### ISSUE TITLE
updateTransactionHistory @ ATM.java writes transactionHistory not as intended

### ISSUE THREAD

**Issue by ghost** [lilhumza/Bank#3]
Currently, it just adds data to the end of the file.
+1234
-123
+1234

Want it to write as
+1234 -123 +1234

**Comment by lilhumza** [comment]
This Code does the trick

               try {
			
			FileWriter out = new FileWriter(textFile);
			BufferedWriter writeFile = new BufferedWriter(out);
			
			writeFile.write(fName);
			writeFile.newLine();
			writeFile.write(lName);
			writeFile.newLine();
			writeFile.write(String.valueOf(accNum));
			writeFile.newLine();
			writeFile.write(String.valueOf(accPin));
			writeFile.newLine();
			
			if (transactionHistory.size() > 0) {
				for (int i = 0; i < transactionHistory.size(); i++) {
					writeFile.write(transactionHistory.get(i)+" ");
				}
			}
			
			writeFile.close();
			out.close();
			
			System.out.println("Account Updated");
		} catch (IOException e) {
				System.err.println("IOException: " + e.getMessage());
		}
