### ISSUE TITLE
Please Link ATM & Bank Teller

### ISSUE THREAD

**Issue by ghost** [lilhumza/Bank#4]
The code is now getting complicated. So please start to work on bank.java. Create and ask for any variables you need. @lilhumza

**Comment by alk0rani** [comment]
@lilhumza is at a hackathon right now, but I've worked on it. Are you using the "Bank" main class in the github in your code? If not, my main is uploaded as "BankQuestion" and you can see if that works with you or not.

**Comment by ghost** [comment]
We’ll work on it at school

**Comment by alk0rani** [comment]
Sounds good.
