### ISSUE TITLE
Deposit + Withdraw - BankTeller

### ISSUE THREAD

**Issue by alk0rani** [lilhumza/Bank#8]
Nice job @lilhumza and hope you enjoying your trip. I don't understand anything you did in the FileEncryption class but it seems pretty sick. **Question**: is it possible for you to deposit and withdraw while accessing from BankTeller (since the program needs to be able to do that)?

**Comment by ghost** [comment]
I made the file encryptions btw. Also I’ll just add my methods for withdraw/deposit to the bank tellers cases

**Comment by ghost** [comment]
Also there needs to be a major rework for bank.java

**Comment by alk0rani** [comment]
Alright, sounds good.

**Comment by alk0rani** [comment]
Major rework in what way?

**Comment by alk0rani** [comment]
Major rework in what way?

**Comment by ghost** [comment]
Needs better flow, we’ll do it on Monday.

**Comment by alk0rani** [comment]
Okay, will do. @Draftyshark
